### ISSUE TITLE
Why the blurb of not recommended on Windows?

### ISSUE THREAD

**Issue by moshen** [jart/landlock-make#2]
On the linked site there is this blurb in the description (emphasis mine):

> Here's a patched prebuilt binary of Landlock Make. This binary is fully-featured on Linux and OpenBSD. On Mac, FreeBSD, and NetBSD it should be a good GNU Make replacement that doesn't do sandboxing. ***On Windows, it kind of works, but isn't recommended.***

Just wondering what the issue is. Thank you!

**Comment by moshen** [comment]
I've noticed that you've changed the wording:

> Here's a patched prebuilt fat binary of Landlock Make for x86-64 and Arm64 operating systems. Sandboxing is only supported on Linux and OpenBSD. **_For the other platforms, you've just got a nice portable drop-in replacement for the GNU make command._**

I've been using this for some Windows work and so far it's been great. I've even created some Makefile / Powershell combos that are... something. Thank you for all your amazing software.

**Comment by jart** [comment]
Thanks! Are you using the landlockmake-2.0.com binary on the website? https://justine.lol/make/ Try using the `make` binary on https://cosmo.zip/pub/cosmos/bin/ it's even better.

**Comment by jart** [comment]
For example, the cosmos make binary is able to do like `make -j80` on my windows computer to build the cosmo repo. It uses `posix_spawn()` so there's no `fork()` overhead. Getting signals and process management to work just right, to make this possible, took some heroics you can read about here: https://justine.lol/cosmo3/ Naturally this all happened after the Landlock Make blog post was published. What I need to do is re-implement all our pledge/unveil stuff on top of `posix_spawn()` at the latest version of GNU Make, since we updated it recently. Then I'll be able to publish again a version of Landlock Make that works great for all platforms.

**Comment by moshen** [comment]
> Are you using the landlockmake-2.0.com binary on the website?

Yes, I've been using `make.com`

> Try using the make binary on https://cosmo.zip/pub/cosmos/bin/ it's even better

Amazing! I think I missed this release. All I had to change was my shell reference to `bash.exe` from `bash`

> For example, the cosmos make binary is able to do like make -j80 on my windows computer to build the cosmo repo

!! Time to try this out :)

Thank you
